### ISSUE TITLE
Internet explorer nao esta funcionando.

### ISSUE THREAD

**Issue by heat** [nodebr/NodeBR.com#2]
Esta todo quebrado o site quando visto do ie10 e ie9

**Comment by rafaeldaime** [comment]
Não estou conseguindo identificar o problema no layout, testado no IE 8 e no IE 10.

**Comment by rafaeldaime** [comment]
Aqui estão fotos tiradas do blog pelo portal http://browsershots.org/ e nós vemos que tanto no [Microsoft Internet Explorer 9] quanto no [Microsoft Internet Explorer 10] não tivemos problemas no layout. Testei também no meu computador IE10 e no do meu trabalho e também não tive problemas. Favor refazer os testes em sua máquina, ou testar em uma outra máquina para ver se encontra os mesmos problemas.

![Microsoft Internet Explorer 9](https://f.cloud.github.com/assets/4377526/516304/7ff929c2-bea7-11e2-87dd-9a58f1fd3203.png)
![Microsoft Internet Explorer 10](https://f.cloud.github.com/assets/4377526/516305/7ffdd8d2-bea7-11e2-9144-9651a0af72ec.png)

**Comment by rafaeldaime** [comment]
Após outra reclamação as cores foram alteradas para as padrões do Twitter Bootstrap.

https://github.com/nodebr/NodeBR.com/commit/a5651b8212cc3401ddfb81c875e8a3dfba47fbdd
