### ISSUE TITLE
Melhorias no sidebar

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [nodebr/NodeBR.com#4]
+Incluir gravatar, links de blogs/sites, twitters e etc no sidebar dos autores.

+Incluir sidebar com links de blogs amigos.

**Comment by rafaeldaime** [comment]
Vou fazer isto agora, já era previsto.
Valeu

**Comment by rafaeldaime** [comment]
Adicionado modificações no modelo do cabeçalho dos posts adicionando campos para o autor preencher com o nome, email, url, usuário do github e usuário do twitter. Acho que isto já fica bem abrangente.
A questão do gravatar é um pouco mais complexa, pois o gravatar é gerado por uma função hash em cima do email, como o github pages não roda códigos ruby de terceiros, apenas o jekyll, então ainda precisa ser estudada uma solução de contorno.
Com relação aos links de blogs amigos na sidebar o que poderia ser pensado é se é viável a adição de mais um meta-dado no cabeçalho dos posts contendo links externos, ou links de referência. Levando em consideração os outros sites da comunidade node internacional (howtonode e nodejitsu), nenhum dispõe disso. A gente pode deixar esta discussão para o futuro.
Valeu de novo!

**Comment by caio-ribeiro-pereira** [comment]
E se migrar o blog de Ruby Jekyll para Node.js Docpad? Além de melhor e ele seria em Node.js eae poderíamos usar esse módulo https://github.com/emerleite/node-gravatar para aplicar o email gravatar e gerar sua respectiva imagem.

**Comment by rafaeldaime** [comment]
Por que você acha que melhoraria em algo? Node.js não é o tipo de framework
que eu usaria para gerar conteúdos estáticos, ele é muito bom usado para
aplicações específicas, não que ele não gere, mas ele é bom para outra
parcela do mercado, Node é ótimo em aplicações em tempo real altamente
exigentes, não gerando conteúdos estáticos... este conceito de viciar em
uma tecnologia e usá-la para tudo é para amadores, Jekyll é ótimo no que
faz e é usado para gerar as páginas estáticas do GitHub todo, ele tem
framework para gravatar, só estou estudando outra forma de inserir a imagem
do author.

Em 17 de maio de 2013 08:26, Caio Ribeiro Pereira
notifications@github.comescreveu:
