### ISSUE TITLE
Menu e Logo 

### ISSUE THREAD

**Issue by paulohp** [nodebr/NodeBR.com#6]
Não sei se é só aqui, mas esse menu azul está de difícil leitura. Sugiro tons mais claros.
A logo também está distorcida.

**Comment by rafaeldaime** [comment]
Valeu paulohb pelo toque, as cores foram alteradas para as cores padrões do Twitter Bootstrap, favor checar e ver se a acessibilidade ficou boa em seu navegador, e deixar o nome e a versão de seu navegador.

Obrigado novamente.

**Comment by rafaeldaime** [comment]
https://github.com/nodebr/NodeBR.com/commit/a5651b8212cc3401ddfb81c875e8a3dfba47fbdd

O logotipo eu realmente não sei o que falar, você pode descrever melhor o que seria distorcido?!
